export class UiConstants {
  static readonly PRESENT_2: string = '2%'
  static readonly PRESENT_4: string = '4%'
  static readonly PRESENT_6: string = '6%'
  static readonly PRESENT_8: string = '8%'
  static readonly PRESENT_10: string = '10%'
  static readonly PRESENT_12: string = '12%'
  static readonly PRESENT_16: string = '16%'
  static readonly PRESENT_20: string = '20%'
  static readonly PRESENT_24: string = '24%'
  static readonly PRESENT_32: string = '32%'
  static readonly PRESENT_40: string = '40%'
  static readonly PRESENT_50: string = '50%'
  static readonly PRESENT_64: string = '64%'
  static readonly PRESENT_70: string = '70%'
  static readonly PRESENT_74: string = '74%'
  static readonly PRESENT_80: string = '80%'
  static readonly PRESENT_84: string = '84%'
  static readonly PRESENT_88: string = '88%'
  static readonly PRESENT_90: string = '90%'
  static readonly PRESENT_92: string = '92%'
  static readonly PRESENT_94: string = '94%'
  static readonly PRESENT_96: string = '96%'
  static readonly PRESENT_100: string = '100%'
  static readonly SPACE_SM = 4
  static readonly SPACE_MD = 10
  static readonly SPACE_LG = 16

  static readonly POSITION_CENTER = 0x1
  static readonly POSITION_TOP = 0x2
  static readonly POSITION_BOTTOM = 0x4
}
